# Generated by Django 4.2.16 on 2026-04-23 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_emission', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('total_energy', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('intensity', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('yoy', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CalcTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.entrymonthlydata')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CalcResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=128)),
                ('metric_value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='calculation.calcresult')),
            ],
        ),
        migrations.AddField(
            model_name='calcresult',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='calculation.calctask'),
        ),
    ]
