# Generated by Django 4.2.16 on 2026-04-23 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('factor_type', models.CharField(default='排放因子', max_length=64)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CalcTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('industry', models.CharField(max_length=128)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CalcBoundaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('item_type', models.CharField(default='过程排放', max_length=64)),
                ('formula', models.TextField(blank=True)),
                ('factor_ref', models.CharField(blank=True, max_length=128)),
                ('sort', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_items', to='calc_config.calctemplate')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
