# Generated by Django 4.2.16 on 2026-04-23 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('emission', '排放报告'), ('energy', '能耗报告'), ('warning', '告警报告')], default='emission', max_length=32)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=1)),
                ('total_emission', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('total_energy', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('value_added', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='generated', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.reportrecord')),
            ],
        ),
    ]
